### ISSUE TITLE
IslandCollect02---overlapping display

### ISSUE THREAD

**Issue by chihpudai** [byungkim82/taskplanner#1]
<img width="616" alt="Screenshot 2020-07-07 23 20 34" src="https://user-images.githubusercontent.com/60309037/86871672-bf9d0980-c0a8-11ea-8763-2fa5003e2d32.png">

There is a minor issue with overlapping "check mark" and the "scrolling arrow." 

(in Google Chrome it's fine.)

**Comment by byungkim82** [comment]
What web browser did you use for the testing?

**Comment by chihpudai** [comment]
Yeah, I figured. It works fine in Google Chrome. I used Safari.

**Comment by byungkim82** [comment]
All right. I will try resolving this issue using other web browsers.

**Comment by byungkim82** [comment]
I hid the arrows on the number input field.
