### ISSUE TITLE
IslandCollect02---correct answer 

### ISSUE THREAD

**Issue by chihpudai** [byungkim82/taskplanner#2]
<img width="1195" alt="Screenshot 2020-07-07 23 42 54" src="https://user-images.githubusercontent.com/60309037/86873097-a77ab980-c0ab-11ea-9da8-e90a965ac64f.png">

<img width="1202" alt="Screenshot 2020-07-07 23 43 41" src="https://user-images.githubusercontent.com/60309037/86873136-b9f4f300-c0ab-11ea-892b-c5999c4c243c.png">

If I am not wrong, the answer is 10?

**Comment by byungkim82** [comment]
You are right. The correct answer is 10. I have updated the numbers to fix this issue. Thanks!
