### ISSUE TITLE
DesertCopy01 - Clicking "get total" keeps generating entry boxes

### ISSUE THREAD

**Issue by pseudoakiba** [byungkim82/taskplanner#3]
![TP_DesertCopy01_click_get_total_spawns_multiple_entrybox](https://user-images.githubusercontent.com/48812109/86874521-88315b80-c0ae-11ea-8ab5-8947b33d3e0e.PNG)

**Comment by byungkim82** [comment]
Thank you so much for finding this issue. I think this came from the old version of the Building task planner, so I would like you to play the new version. The links are on the main page of this repository.
