### ISSUE TITLE
DesertPlacement

### ISSUE THREAD

**Issue by seydauysal** [byungkim82/taskplanner#4]
![Screen Shot 2020-07-08 at 1 33 34 PM](https://user-images.githubusercontent.com/43488302/86951649-cfa40000-c11f-11ea-8aaf-746c3d3c9ead.png)
When I clicked on proceed, nothing happens. Should it allow me to proceed further?
Also, there is no rotation option for roof placement? The houses always square?

**Comment by byungkim82** [comment]
Which game level did you play? At the end of the placing task planner, you should get a notification saying "Great Job! All you need to do is to reposition the buildings/objects to the designated location after the transformations.". No problem at all on my end. Did you use Chrome browser?

**Comment by byungkim82** [comment]
Regarding the rotation option, I have added it to the multiple-choice options. Thanks for the comment!

**Comment by seydauysal** [comment]
I think the level was desertcopy01. I tested the levels in Safari. Thanks for addressing the feedback.
