### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by seydauysal** [byungkim82/taskplanner#5]
![Screen Shot 2020-07-08 at 1 27 27 PM](https://user-images.githubusercontent.com/43488302/86951849-12fe6e80-c120-11ea-97d0-26313b1615ca.png)

When I clicked on the image button, I was not able to view the image shown under the question. It did not allow me to scroll down the page.

**Comment by byungkim82** [comment]
Resolved. You can scroll down to see the overflown content in the modal.
