### ISSUE TITLE
Allocating - "Proceed" button should close window

### ISSUE THREAD

**Issue by pseudoakiba** [byungkim82/taskplanner#7]
On Allocating, the "proceed" button after entering the space for one fish changes color after clicking, but does not close the current window and advance the user to the next step.
![image](https://user-images.githubusercontent.com/48812109/87182527-5688e200-c2b2-11ea-9116-7e989e4fda55.png)

**Comment by byungkim82** [comment]
on which game level?

**Comment by pseudoakiba** [comment]
Sry, FarmVolume01

**Comment by byungkim82** [comment]
Proceed button is working now. I have also replaced the plural form of fish in the DB. Thanks for the feedback!
